/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.common {
    export class CommonButtonUI extends View {
		public img_bg:Laya.Image;
		public img_normal:Laya.Image;
        public static  uiView:any ={"type":"View","props":{"width":300,"height":200},"compId":2,"child":[{"type":"Image","props":{"var":"img_bg","centerY":0,"centerX":0},"compId":3},{"type":"Image","props":{"var":"img_normal","centerY":0,"centerX":0},"compId":6}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(CommonButtonUI.uiView);
        }
    }
    REG("ui.common.CommonButtonUI",CommonButtonUI);
    export class CommonCounterUI extends View {
		public img_bg:Laya.Sprite;
        public static  uiView:any ={"type":"View","props":{"width":72,"height":48},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":72,"var":"img_bg","height":48},"compId":3}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(CommonCounterUI.uiView);
        }
    }
    REG("ui.common.CommonCounterUI",CommonCounterUI);
    export class SingleCounterItemUI extends View {
		public img_top:Laya.Image;
		public label_num:Laya.Label;
		public btn_unit:any;
		public sp_groung:Laya.Sprite;
		public box_zhu:Laya.Box;
        public static  uiView:any ={"type":"View","props":{"width":148,"height":895},"compId":2,"child":[{"type":"Box","props":{"width":148,"top":0,"height":108,"centerX":0},"compId":14,"child":[{"type":"Image","props":{"var":"img_top","centerY":0,"centerX":0},"compId":3},{"type":"Label","props":{"var":"label_num","fontSize":80,"font":"Arial","color":"#ffffff","centerY":6,"centerX":0},"compId":5}]},{"type":"CommonButton","props":{"width":134,"var":"btn_unit","runtime":"script/core/view/common/CommonButton.ts","height":98,"centerX":0,"bottom":0},"compId":4},{"type":"Sprite","props":{"y":756,"x":0,"width":148,"var":"sp_groung","height":2,"alpha":0},"compId":7,"child":[{"type":"Script","props":{"type":"static","runtime":"Laya.RigidBody"},"compId":8},{"type":"Script","props":{"y":0,"x":0,"width":148,"label":"ground","height":2,"runtime":"Laya.BoxCollider"},"compId":9}]},{"type":"Box","props":{"width":72,"var":"box_zhu","height":546,"centerX":0,"bottom":139},"compId":6}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(SingleCounterItemUI.uiView);
        }
    }
    REG("ui.common.SingleCounterItemUI",SingleCounterItemUI);
}
export module ui.main {
    export class ConfirmViewUI extends View {
		public btn_cancle:any;
		public btn_yes:any;
        public static  uiView:any ={"type":"View","props":{"width":576,"height":284},"compId":2,"child":[{"type":"Sprite","props":{"texture":"dialog/dialogbg.png"},"compId":3},{"type":"Label","props":{"top":88,"text":"确定重置当前画板吗？","fontSize":34,"font":"FZLTCHJW","color":"#3a6283","centerX":0},"compId":4},{"type":"CommonButton","props":{"width":220,"var":"btn_cancle","top":172,"runtime":"script/core/view/common/CommonButton.ts","left":52,"height":80},"compId":5},{"type":"CommonButton","props":{"width":220,"var":"btn_yes","top":172,"runtime":"script/core/view/common/CommonButton.ts","right":52,"height":80},"compId":6}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(ConfirmViewUI.uiView);
        }
    }
    REG("ui.main.ConfirmViewUI",ConfirmViewUI);
    export class GameViewSceneUI extends Scene {
		public panel_content:Laya.Panel;
		public btn_recall:any;
		public btn_reset:any;
		public btn_guide:any;
        public static  uiView:any ={"type":"Scene","props":{"width":1920,"positionVariance_0":100,"name":"GameViewScene","maxPartices":100,"height":1080},"compId":1,"child":[{"type":"Box","props":{"zOrder":1,"y":0,"x":0,"width":1920,"height":1080,"cacheAs":"bitmap"},"compId":38,"child":[{"type":"Sprite","props":{"y":0,"x":0,"texture":"common/common_bg1.png"},"compId":34},{"type":"Sprite","props":{"y":75,"x":0,"texture":"common/common_bg2.png"},"compId":35},{"type":"Sprite","props":{"y":293,"x":153,"texture":"common/common_bg3.png"},"compId":36}]},{"type":"Panel","props":{"zOrder":2,"width":1920,"var":"panel_content","height":1080,"centerY":0,"centerX":0},"compId":29},{"type":"Image","props":{"zOrder":3,"y":625,"x":1749,"top":625,"skin":"guide/guide_bg.png","right":111},"compId":40},{"type":"CommonButton","props":{"zOrder":4,"width":226,"var":"btn_recall","top":649,"runtime":"script/core/view/common/CommonButton.ts","right":22,"height":114},"compId":31},{"type":"CommonButton","props":{"zOrder":4,"width":226,"var":"btn_reset","top":780,"runtime":"script/core/view/common/CommonButton.ts","right":22,"height":114},"compId":32},{"type":"CommonButton","props":{"zOrder":4,"width":140,"var":"btn_guide","top":926,"runtime":"script/core/view/common/CommonButton.ts","right":62,"height":54},"compId":41}],"loadList":["guide/guide_bg.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(GameViewSceneUI.uiView);
        }
    }
    REG("ui.main.GameViewSceneUI",GameViewSceneUI);
    export class PlayGuideViewUI extends View {
		public panel_content:Laya.Panel;
		public img_bg:Laya.Sprite;
		public btn_close:Laya.Sprite;
		public box_gif:Laya.Sprite;
		public box_point:Laya.Sprite;
		public btn_left:Laya.Sprite;
		public btn_right:Laya.Sprite;
        public static  uiView:any ={"type":"View","props":{"width":1920,"height":1080},"compId":2,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":1920,"texture":"common/maskBg.png","height":1080,"alpha":0.5},"compId":20},{"type":"Panel","props":{"width":892,"var":"panel_content","height":552,"centerY":0,"centerX":0},"compId":7,"child":[{"type":"Sprite","props":{"y":0,"x":0,"width":780,"var":"img_bg","texture":"common/guide_bg.png","height":552},"compId":14},{"type":"Sprite","props":{"y":240,"x":820,"var":"btn_close","texture":"guideView/btn_close.png"},"compId":15},{"type":"Sprite","props":{"y":20,"x":15,"var":"box_gif"},"compId":16},{"type":"Sprite","props":{"y":499,"x":28,"var":"box_point"},"compId":17},{"type":"Sprite","props":{"y":471,"x":419,"var":"btn_left"},"compId":18},{"type":"Sprite","props":{"y":471,"x":591,"var":"btn_right"},"compId":19}]}],"loadList":["guideView/btn_close.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(PlayGuideViewUI.uiView);
        }
    }
    REG("ui.main.PlayGuideViewUI",PlayGuideViewUI);
}